packages:
  - apps/*
  - packages/*

catalog:
  "@babel/core": ^7.29.0
  "@rolldown/plugin-babel": ~0.2.2
  "@types/babel__core": ^7.20.5
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@typescript/native-preview": 7.0.0-dev.20260328.1
  "@vitejs/plugin-react": ^6.0.1
  "@vitejs/plugin-rsc": ~0.5.21
  "babel-plugin-react-compiler": ^1.0.0
  react: canary
  react-dom: canary
  react-server-dom-webpack: canary
  remix: 3.0.0-alpha.4
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-devtools-json: ^1.0.0
  vite-plugin-react-use-cache: 0.0.8
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - react
    - react-dom
    - react-server-dom-webpack
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
